### ISSUE TITLE
预览模式下，鼠标放在标题后方的时候会显示一个“#”号

### ISSUE THREAD

**Issue by Fxiao1** [tamlok/vnote#1112]
OS Version (操作系统): Windows, Linux, macOS
win10
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
2.8
Symptoms (表现):
如标题描述那样。这个“#”号点击也没啥作用，反倒影响复制标题的操作，因为在拖动的时候会变成拖动一个链接，而不是滑动选中标题。请问这个鸡肋如何取消呢？
![Snipaste_2019-12-15_01-14-32](https://user-images.githubusercontent.com/40653617/70852132-d5629b80-1ed8-11ea-9192-73cdd9df4c78.png)

How to Repro (如何复现):
预览模式打开笔记，鼠标放在标题后方即可看见

**Comment by tamlok** [comment]
很多网站都有这个，主要是你可以右键复制到这个标题的一个链接。去掉的话，看看cas能不能搞吧

**Comment by Fxiao1** [comment]
> cas
请问关于这个cas能否详细说说呢？我看是给每个标题后面添加了一个a链接，然后透明度为0，鼠标放上的时候会将透明度变为1，请问怎么禁止这个“将透明度改为1”的动作呢？

**Comment by tamlok** [comment]
css，输入错了~~你看一下v_pure. css 里面相关的控制吧

**Comment by Fxiao1** [comment]
我现在在css里面将所有标题里面的链接禁用了。但这么做有个明显的缺点，就是标题里面如果有其他链接的话也会被禁用了。所以想请问下哪里是改变透明度的地方呢，就是将那个“#”号的透明度从0变成1的地方。如果能从源头上禁止这个“:hover”动作的话，这才是最优解了。
```css
h1>a,h2>a,h3>a,h4>a,h5>a,h6>a {
	display:none;
}
```

**Comment by tamlok** [comment]
看看配置文件夹下面的common.css

**Comment by Fxiao1** [comment]
感谢协助！已解决
解决方法贡献出来
# 解决步骤：
1. 在`文件`菜单点击`打开配置文件夹`
2. 打开`resource`文件夹，找到`common.css`，去掉它的“只读”属性
3. 编辑该文件，找到如下代码
```css
/* Anchor */
.vnote-anchor {
    font-weight: 400;
    color: rgba(0,123,255,.5);
    transition: color .16s linear;
    padding-left: 0.375em;
    -webkit-font-smoothing: antialiased;
    text-decoration: none;
    opacity: 0;
	display:none;
}


.vnote-anchor:hover {
    color: rgba(0,123,255,1);
    text-decoration: none;
    opacity: 1;
}
```
改为如下即可
```css
/* Anchor */
.vnote-anchor {
    /*font-weight: 400;
    color: rgba(0,123,255,.5);
    transition: color .16s linear;
    padding-left: 0.375em;
    -webkit-font-smoothing: antialiased;
    text-decoration: none;
    opacity: 0;*/
	display:none;
}

/*
.vnote-anchor:hover {
    color: rgba(0,123,255,1);
    text-decoration: none;
    opacity: 1;
}
*/
```
# 需要注意的点：
`common.css`这个文件是有可能被清除的，应该是不会自动清除，但是有时候更改别的项，碍于生效慢，有可能会手动清除，让其重新生成，所以改动的地方自己需要心里清楚。如果该文件重新生成导致还原了，还需要知道怎么修改好。
