### ISSUE TITLE
Is there any way to change the style of the note label in the VNote status bar?

### ISSUE THREAD

**Issue by JeffreySE** [tamlok/vnote#322]
Is there any way to change the style of the note label in the VNote status bar?
Well, in fact, this is not a problem, it does not affect normal use.

**Environment**
- VNote version：v1.20
- OS: Win10 x64

VNote is very cool, I use it everyday, thank you @tamlok you did a great job, keep going

Well , I just want to change the  behavior of the note label when mouse moves hover the note label.

**e.g.**
Default style of note label:
![image](https://user-images.githubusercontent.com/12522179/43191222-50757360-902d-11e8-8f3d-359fb58edec1.png)

When mouse moves hover:
![2](https://user-images.githubusercontent.com/12522179/43191440-c2256092-902d-11e8-83f6-0b23cd37d18a.png)

I have a custom VNote theme style, but I don't know where to modify the VNote status bar's style.
I'm not familiar with QT, I just found this in `.qss` theme file.

```css
QLabel[TagLabel="true"] {
    padding-left: $5px;
    padding-right: $5px;
    color: @tab_indicator_tag_label_fg;
    border-top-left-radius: $10px $8px;
    border-bottom-left-radius: $10px $8px;
    background-color: @tab_indicator_tag_label_bg;
}
```

Can anyone tell me how to implement the following changes?
- remove `...` when label text is much longer
- keep border left radius default
- don't change the status bar's height, on mouse hover event

Anyone who can help will be much appreciated
